### ISSUE TITLE
Pin 1 indicator is not visible on manufactured boards due to silkscreen-to-mask clearance

### ISSUE THREAD

**Issue by mrnuke** [KiCad/Housings_SOIC.pretty#10]
The small line that is supposed to be the pin 1 indicator is too close to pad 1. Once soldermask clearance is taken into account, the silkscreen line would end up falling on bare FR4. This happens with 0.15 mm pad mask clearance.

I've tested Oshpark and seedstudio, and with both manufacturers, the pin1 indicator line is removed, and there is no way to identify the correct orientation of the footprint.

![img_20160725_204914](https://cloud.githubusercontent.com/assets/2610559/17125616/e93f8d1a-52a9-11e6-9a12-3d580090854f.jpg)

**Comment by SchrodingersGat** [comment]
@mrnuke have a look at this PR - https://github.com/KiCad/Housings_SOIC.pretty/pull/9

I have now updated it to include a fix for this by moving the pin-1 indication away from the solder mask

**Comment by CarlPoirier** [comment]
#9 is merged, closing this.
