### ISSUE TITLE
Pads positions / size are a little bit small

### ISSUE THREAD

**Issue by LTI-BA** [KiCad/Housings_SOIC.pretty#12]
compared the dimensions of the footprint with those from Si823x gate driver family. The pads are a bit too small and the footprint is not wide enough.

Check this footprint I found : 
LTI-BA/Footprints/blob/master/SOIC-16_3.9x9.9mm_Pitch1.27mm.kicad_mod

**Comment by evanshultz** [comment]
@LTI-BA 
The [3.9x9.9mm package](https://github.com/KiCad/Housings_SOIC.pretty/blob/master/SOIC-16_3.9x9.9mm_Pitch1.27mm.kicad_mod) you mentioned is the narrow body package. Here is the drawing from them [Si823x datasheet](https://www.silabs.com/documents/public/data-sheets/Si823x.pdf):
![image](https://user-images.githubusercontent.com/1936989/28335625-e39b654a-6bb3-11e7-9489-195cdcef5e30.png)

The row-to-row spacing is 5.4mm on both footprints, and of course pin pitch is 1.27mm.

Pad sizes in the library footprint are 1.5x0.6mm while Si Labs says 1.55x0.6mm. Having pads 0.05mm less wide than what Si Labs recommends, on this particular part, is insignificant.

I don't see a problem here, so please reply with more details of the issue you see. If I don't see a reply within a few days I'll close this issue.

**Comment by evanshultz** [comment]
I forgot to also mention that the actual part body dimensions exactly match: 3.9mm and 9.9mm. Datasheet:
![image](https://user-images.githubusercontent.com/1936989/28376189-54d535b0-6c5e-11e7-9d78-0590db825b60.png)
