### ISSUE TITLE
Is there a footprint-generator script for SOIC/SO housings?

### ISSUE THREAD

**Issue by Schlumpf** [KiCad/Housings_SOIC.pretty#32]
Is there a footprint-generator script for SOIC/SO housings?
I didn't find anything...

**Comment by poeschlr** [comment]
Doesn't look like ther is:
https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts

But maybe in someones fork?

**Comment by SchrodingersGat** [comment]
@Schlumpf I'm closing this issue as I am locking the repository. Please readdress this to https://github.com/kicad/kicad-footprints if you think it needs further attention :)
