### ISSUE TITLE
Pads too long

### ISSUE THREAD

**Issue by greenscreenflicker** [KiCad/Housings_SOIC.pretty#7]
I used SOIC8 footprint  (small one: 3.9x4.9) and the pads are far too long. I will correct this, and issue a pull request soon.

**Comment by SchrodingersGat** [comment]
@greenscreenflicker when you do, make sure you add in a datasheet to show the size of the new pads. I think what we should do is add a longer-pad version with a _HandSoldering suffix, if appropriate.

**Comment by greenscreenflicker** [comment]
Ok, allright.

**Comment by greenscreenflicker** [comment]
Checked this footprint. It's according to specification. My fault.
